
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      # 启用基本认证
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      # 外网可访问的 webhook 地址（根据实际域名或 IP 修改）
      - WEBHOOK_URL=http://localhost:5678/
      # 时区设置为欧洲/阿姆斯特丹
      - GENERIC_TIMEZONE=Europe/Amsterdam
    volumes:
      # n8n 配置与数据持久化
      - n8n_data:/home/node/.n8n
      # 本地文件访问（可选，映射到 /files）
      - ./local_files:/files
    restart: unless-stopped

volumes:
  n8n_data:
